import { boolean, index, integer, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const accessEnum=pgEnum('access_level',['free','premium','patient','institutional']);
export const entitlementStatus=pgEnum('entitlement_status',['active','inactive','expired']);

export const users=pgTable('users',{id:uuid('id').defaultRandom().primaryKey(),authUserId:text('auth_user_id').notNull(),email:text('email'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('users_auth_user_idx').on(t.authUserId)]);
export const contentItems=pgTable('content_items',{id:text('id').primaryKey(),slug:text('slug').notNull(),title:text('title').notNull(),access:accessEnum('access').default('free').notNull(),published:boolean('published').default(false).notNull(),version:text('version').notNull()},t=>[uniqueIndex('content_slug_idx').on(t.slug)]);
export const entitlements=pgTable('entitlements',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),level:accessEnum('level').notNull(),status:entitlementStatus('status').default('active').notNull(),source:text('source').notNull(),externalRef:text('external_ref'),expiresAt:timestamp('expires_at',{withTimezone:true}),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('entitlement_user_idx').on(t.userId)]);
export const progress=pgTable('progress',{userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),contentId:text('content_id').references(()=>contentItems.id,{onDelete:'cascade'}).notNull(),positionSeconds:integer('position_seconds').default(0).notNull(),completed:boolean('completed').default(false).notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull()},t=>[primaryKey({columns:[t.userId,t.contentId]})]);
export const favorites=pgTable('favorites',{userId:uuid('user_id').references(()=>users.id,{onDelete:'cascade'}).notNull(),contentId:text('content_id').references(()=>contentItems.id,{onDelete:'cascade'}).notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[primaryKey({columns:[t.userId,t.contentId]})]);
export const purchases=pgTable('purchases',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').references(()=>users.id,{onDelete:'set null'}),provider:text('provider').notNull(),externalId:text('external_id').notNull(),status:text('status').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('purchase_external_idx').on(t.provider,t.externalId)]);
export const auditEvents=pgTable('audit_events',{id:uuid('id').defaultRandom().primaryKey(),event:text('event').notNull(),subjectId:text('subject_id'),requestId:text('request_id'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('audit_event_idx').on(t.event)]);
