import type { TrackId } from '@/components/glyphs';

export type Access='free'|'premium'|'patient'|'institutional';
export type AudioState='legacy-rewrite'|'script-approved'|'master-approved';
export type Pill={
  id:string;slug:string;title:string;shortTitle:string;track:TrackId;skill:string;description:string;reading:string[];reflection:string;
  access:Access;audioState:AudioState;legacyAudio?:string;visual?:'flow'|'cycle'|'wave'|'compare';
};

export const tracks:{id:TrackId;name:string;description:string}[]=[
  {id:'pensamentos',name:'Pensamentos',description:'Perceber pensamentos com mais clareza e responder a eles com mais flexibilidade.'},
  {id:'emocoes',name:'Emoções',description:'Reconhecer emoções, compreender sua função e ampliar possibilidades de resposta.'},
  {id:'acao',name:'Ação e comportamento',description:'Transformar compreensão em pequenas ações possíveis no cotidiano.'},
  {id:'regulacao',name:'Presença e regulação',description:'Orientar atenção, desacelerar e recuperar espaço de escolha.'},
  {id:'autoconhecimento',name:'Autoconhecimento',description:'Explorar valores, padrões e maneiras de se relacionar consigo.'},
  {id:'cotidiano',name:'Vida cotidiana',description:'Reflexões sobre comparação, tédio, rotina, relações e presença.'},
];

export const pills:Pill[]=[
{id:'pr-001',slug:'pensamento-nao-e-fato',title:'Pensamento não é fato',shortTitle:'Pensamento ≠ fato',track:'pensamentos',skill:'distanciamento cognitivo',description:'Separe aquilo que aconteceu da interpretação que sua mente produziu.',reading:['A mente interpreta o tempo todo. Ela preenche lacunas, antecipa possibilidades e tenta dar sentido ao que acontece. Uma interpretação pode parecer tão convincente que passa a ser tratada como fato.','Quando um pensamento vier acompanhado de certeza, experimente separar o acontecimento observável, a interpretação e as evidências disponíveis. O objetivo não é pensar positivo. É pensar com mais precisão.'],reflection:'Qual pensamento você tratou hoje como fato antes de verificar as evidências?',access:'free',audioState:'script-approved',visual:'flow'},
{id:'pr-002',slug:'registro-de-pensamentos',title:'Registro de pensamentos na prática',shortTitle:'Registro de pensamentos',track:'pensamentos',skill:'monitoramento cognitivo',description:'Organize situação, pensamentos, emoções e respostas sem transformar reflexão em julgamento.',reading:['O registro desacelera uma experiência que, por dentro, costuma acontecer muito rápido. Situação, interpretação, emoção e comportamento podem se misturar como se fossem uma única coisa.','Descreva primeiro o que aconteceu de forma observável. Depois registre o pensamento, a emoção e o que você fez. Só então explore outras interpretações possíveis.'],reflection:'Se você registrasse apenas uma situação de hoje, qual escolheria?',access:'free',audioState:'legacy-rewrite',legacyAudio:'PODCAST 000 REGISTRO DE PENSAMENTOS DISFUNCIONAIS.mp3'},
{id:'pr-003',slug:'quando-um-pensamento-nao-vai-embora',title:'Quando um pensamento não vai embora',shortTitle:'Pensamentos persistentes',track:'pensamentos',skill:'flexibilidade cognitiva',description:'Mude a relação com pensamentos persistentes sem precisar vencer uma disputa mental.',reading:['Quanto mais urgente parece a necessidade de expulsar um pensamento, mais atenção ele pode receber. Em vez de discutir com ele imediatamente, experimente reconhecê-lo como um evento mental.','Você não precisa concordar com um pensamento para notar que ele apareceu. Também não precisa obedecê-lo. Observe, nomeie e escolha o que merece sua atenção agora.'],reflection:'O que muda quando você troca “preciso parar de pensar nisso” por “percebo que minha mente voltou a esse assunto”?',access:'free',audioState:'legacy-rewrite',legacyAudio:'PODCAST 002 LIDANDO COM PENSAMENTOS DE CONTROLE.mp3'},
{id:'pr-004',slug:'ruminacao-quando-pensar-nao-ajuda',title:'Ruminação: quando pensar deixa de ajudar',shortTitle:'Ruminação',track:'pensamentos',skill:'metacognição',description:'Diferencie reflexão útil de repetição mental que gira em torno do problema.',reading:['Refletir pode produzir compreensão, decisão ou ação. Ruminar costuma produzir repetição. A mesma pergunta retorna e novas respostas parecem insuficientes.','Pergunte: existe alguma ação concreta e proporcional que posso realizar agora? Se sim, defina o menor próximo passo. Se não, experimente devolver atenção ao que está diante de você.'],reflection:'Este pensamento está me aproximando de uma ação possível ou apenas repetindo a mesma pergunta?',access:'free',audioState:'script-approved',visual:'cycle'},
{id:'pr-005',slug:'conviver-com-a-incerteza',title:'Quando não existe certeza suficiente',shortTitle:'Incerteza',track:'pensamentos',skill:'tolerância à incerteza',description:'Reconheça quando a busca por certeza deixa de proteger e começa a consumir energia.',reading:['Buscar informação pode ser útil. Buscar certeza absoluta muitas vezes não tem ponto claro de chegada. Sempre pode existir mais uma checagem ou cenário possível.','Defina qual nível de informação é suficiente para uma decisão razoável. Depois observe o desconforto de não saber tudo sem transformá-lo em nova checagem automática.'],reflection:'Qual decisão sua está esperando uma certeza que talvez não exista?',access:'premium',audioState:'script-approved'},
{id:'pr-006',slug:'ansiedade-o-corpo-em-alerta',title:'Ansiedade: o corpo em alerta',shortTitle:'Ansiedade e alerta',track:'emocoes',skill:'psicoeducação emocional',description:'Entenda como ameaça percebida, corpo, atenção e interpretação podem se alimentar mutuamente.',reading:['A ansiedade envolve um sistema de proteção. Quando uma ameaça é percebida, o corpo pode aumentar ativação e a atenção fica mais sensível a sinais de perigo.','O problema não é sentir qualquer ativação. É quando o próprio sinal de ansiedade passa a ser interpretado como prova de que algo terrível está prestes a acontecer.'],reflection:'Quando você fica ansioso, qual sinal do corpo costuma captar primeiro?',access:'free',audioState:'script-approved',visual:'cycle'},
{id:'pr-007',slug:'quando-a-tristeza-pede-espaco',title:'Quando a tristeza pede espaço',shortTitle:'Tristeza',track:'emocoes',skill:'aceitação emocional',description:'Reconheça tristeza sem exigir que ela desapareça imediatamente.',reading:['Nem toda tristeza é um problema a ser resolvido no mesmo instante. Algumas experiências pedem reconhecimento, tempo e cuidado.','Além de “como faço isso passar?”, experimente perguntar “o que esta emoção está sinalizando?” e “de que tipo de cuidado preciso agora?”.'],reflection:'Se sua tristeza pudesse pedir um cuidado concreto hoje, qual seria?',access:'premium',audioState:'script-approved'},
{id:'pr-008',slug:'antes-da-irritacao-explodir',title:'Antes da irritação explodir',shortTitle:'Irritação',track:'emocoes',skill:'regulação emocional',description:'Identifique sinais iniciais de irritação para aumentar o espaço entre impulso e resposta.',reading:['A explosão raramente é o primeiro sinal. Tensão muscular, aceleração da fala, pensamentos absolutos ou urgência para responder podem surgir antes.','Reconhecer esses sinais não elimina o motivo da irritação. Apenas devolve alguns segundos de escolha.'],reflection:'Qual é o seu sinal mais precoce de que a irritação está aumentando?',access:'premium',audioState:'script-approved'},
{id:'pr-009',slug:'inseguranca-e-confianca',title:'Insegurança não precisa decidir por você',shortTitle:'Insegurança',track:'emocoes',skill:'autoeficácia',description:'Construa confiança também pela experiência, sem esperar que ela seja condição para agir.',reading:['Esperar sentir segurança completa antes de agir pode transformar insegurança em regra. Em muitas situações, confiança aumenta depois que acumulamos experiências proporcionais.','A pergunta útil é: qual passo é possível mesmo com alguma insegurança presente?'],reflection:'Qual ação pequena você vem adiando até se sentir totalmente confiante?',access:'premium',audioState:'legacy-rewrite',legacyAudio:'PODCAST 005 SUPERANDO INSEGURANÇA.mp3'},
{id:'pr-010',slug:'aja-antes-de-se-sentir-pronto',title:'Aja antes de se sentir totalmente pronto',shortTitle:'Começar antes da confiança',track:'acao',skill:'experimento comportamental',description:'Teste um comportamento novo antes de exigir motivação ou confiança completas.',reading:['Agir não precisa significar fingir quem você é. Pode significar testar um comportamento novo antes de ter certeza de que ele dará certo.','Escolha uma ação pequena, observável e reversível. Execute-a como experimento. Depois compare sua previsão com o que realmente aconteceu.'],reflection:'Qual comportamento você poderia testar como experimento, sem exigir perfeição?',access:'free',audioState:'legacy-rewrite',legacyAudio:'PODCAST 006 FINJA ATÉ SER VERDADE.mp3'},
{id:'pr-011',slug:'o-ciclo-da-evitacao',title:'O ciclo da evitação',shortTitle:'Evitação',track:'acao',skill:'exposição gradual',description:'Veja por que evitar alivia agora e pode fortalecer a dificuldade depois.',reading:['Evitar costuma funcionar no curto prazo: o desconforto cai. Esse alívio pode ensinar ao cérebro que a fuga foi necessária para ficar seguro.','A alternativa não é se jogar no pior cenário, mas construir aproximações graduais, proporcionais e repetidas.'],reflection:'Qual situação você evita porque o alívio imediato parece valer mais do que o custo futuro?',access:'premium',audioState:'script-approved',visual:'cycle'},
{id:'pr-012',slug:'procrastinacao-e-o-proximo-passo',title:'Procrastinação e o próximo passo',shortTitle:'Procrastinação',track:'acao',skill:'ativação comportamental',description:'Reduza uma tarefa grande até encontrar uma ação pequena o suficiente para começar.',reading:['Muitas tarefas parecem impossíveis porque são representadas como um bloco único. “Fazer o relatório” pode significar dezenas de decisões diferentes.','Troque o projeto inteiro pela próxima ação física e observável: abrir o arquivo, escrever três tópicos, separar documentos.'],reflection:'Qual é a menor ação visível que inicia a tarefa que você está adiando?',access:'premium',audioState:'script-approved'},
{id:'pr-013',slug:'retornar-ao-presente',title:'Uma pausa para retornar ao presente',shortTitle:'Pausa guiada',track:'regulacao',skill:'atenção plena',description:'Oriente a atenção ao momento presente sem obrigação de esvaziar a mente.',reading:['A prática não exige impedir pensamentos. O objetivo é perceber quando a atenção se afasta e experimentar trazê-la de volta com menos luta.','Respiração, sons e sensações corporais podem servir como pontos de referência. Se a prática aumentar desconforto, interrompa e escolha outra forma de se orientar ao ambiente.'],reflection:'Qual ponto de referência ajuda você a perceber que está aqui, agora?',access:'free',audioState:'legacy-rewrite',legacyAudio:'PODCAST 007 MEDITAÇÃO GUIADA.mp3',visual:'wave'},
{id:'pr-014',slug:'aterramento-pelos-sentidos',title:'Aterramento pelos sentidos',shortTitle:'Aterramento',track:'regulacao',skill:'orientação sensorial',description:'Use o ambiente como âncora quando sua atenção estiver presa a pensamentos ou sensações internas.',reading:['Aterramento é orientar deliberadamente a atenção ao ambiente presente. Observe formas, temperaturas, texturas, sons e pontos de contato do corpo.','Não precisa transformar isso em contagem rígida. O essencial é trocar, por alguns instantes, a atenção abstrata pela informação sensorial disponível agora.'],reflection:'Qual detalhe do ambiente você não tinha percebido até alguns segundos atrás?',access:'premium',audioState:'script-approved'},
{id:'pr-015',slug:'pausa-entre-impulso-e-acao',title:'Uma pausa entre impulso e ação',shortTitle:'Pausa e escolha',track:'regulacao',skill:'controle inibitório',description:'Crie uma pequena janela de escolha antes de responder automaticamente a um impulso.',reading:['Impulso não é ordem. Ele é informação acompanhada de urgência. Quanto maior a ativação, menor pode parecer o espaço entre sentir vontade e agir.','Treine uma sequência curta: perceber, nomear, pausar e escolher. A pausa pode durar poucos segundos.'],reflection:'Em qual situação alguns segundos de pausa fariam diferença para você?',access:'premium',audioState:'script-approved',visual:'flow'},
{id:'pr-016',slug:'fomo-e-comparacao',title:'FOMO: quando parece que todos estão vivendo mais',shortTitle:'FOMO',track:'cotidiano',skill:'comparação social consciente',description:'Observe o medo de ficar de fora e retorne àquilo que realmente merece sua presença.',reading:['Nas redes vemos recortes selecionados da vida de outras pessoas e podemos compará-los com a experiência completa da nossa própria vida. Essa comparação é estruturalmente desigual.','Pergunte menos “o que estou perdendo?” e mais “o que estou deixando de perceber enquanto acompanho o que os outros fazem?”.'],reflection:'O que merece mais presença sua do que comparação neste momento?',access:'premium',audioState:'legacy-rewrite',legacyAudio:'PODCAST 003 LIDANDO COM FOMO.mp3'},
{id:'pr-017',slug:'tedio-e-inquietacao',title:'Quando tudo parece tédio ou inquietação',shortTitle:'Tédio e inquietação',track:'cotidiano',skill:'tolerância ao desconforto',description:'Use o pêndulo de Schopenhauer como lente, não como destino.',reading:['A metáfora do pêndulo ajuda a perceber como buscamos estímulo quando o vazio incomoda e descanso quando o excesso cansa. Ela é uma lente filosófica, não uma regra sobre a vida.','Em vez de fugir automaticamente do tédio, observe o que aparece quando não há estímulo imediato.'],reflection:'O que costuma aparecer quando você não preenche imediatamente o silêncio ou o tédio?',access:'premium',audioState:'legacy-rewrite',legacyAudio:'PODCAST 004 LIDANDO COM O TÉDIO.mp3'},
{id:'pr-018',slug:'renovar-o-domingo',title:'Fechando o domingo com menos cobrança',shortTitle:'Domingo à noite',track:'cotidiano',skill:'transição de rotina',description:'Organize expectativas para entrar na semana sem tentar viver todos os dias de uma vez.',reading:['Domingo à noite pode concentrar antecipações sobre tudo o que ainda não aconteceu. Organizar a semana ajuda; tentar viver mentalmente todos os dias de uma vez costuma aumentar o peso.','Escolha apenas o primeiro compromisso relevante de amanhã e uma ação simples de preparação.'],reflection:'O que realmente precisa estar decidido hoje — e o que pode esperar até amanhã?',access:'free',audioState:'legacy-rewrite',legacyAudio:'PODCAST 001 OUVIR NO FINAL DE DOMINGO.mp3'},
{id:'pr-019',slug:'valores-nao-sao-metas',title:'Valores não são metas',shortTitle:'Valores × metas',track:'autoconhecimento',skill:'clarificação de valores',description:'Diferencie destinos específicos de direções de vida que orientam escolhas repetidas.',reading:['Uma meta pode ser concluída. Um valor funciona mais como direção: aprender, cuidar, contribuir, criar ou cultivar relações significativas.','Metas podem servir aos valores, mas não são a mesma coisa. Quando uma meta falha, o valor ainda pode orientar o próximo movimento.'],reflection:'Qual direção você gostaria que aparecesse mais claramente nas suas escolhas desta semana?',access:'premium',audioState:'script-approved',visual:'compare'},
{id:'pr-020',slug:'o-critico-dentro-da-cabeca',title:'O crítico dentro da cabeça',shortTitle:'Autocrítica',track:'autoconhecimento',skill:'autocompaixão responsável',description:'Diferencie uma crítica que orienta correção de uma voz interna que transforma erro em identidade.',reading:['Autocrítica pode parecer uma estratégia para evitar acomodação. O problema surge quando a avaliação deixa de ser sobre comportamento e passa a definir a pessoa inteira.','Responsabilidade e autocompaixão não são opostos. Você pode reconhecer um erro, reparar o que for possível e falar consigo de um modo que favoreça aprendizagem.'],reflection:'Se você mantivesse a responsabilidade, mas retirasse a humilhação, o que diria a si mesmo?',access:'premium',audioState:'script-approved',visual:'flow'},
];

export function getPill(slug:string){return pills.find(p=>p.slug===slug)}
export function getTrack(id:TrackId){return tracks.find(t=>t.id===id)}
