'use client';

import { useEffect, useRef, useState } from 'react';
import { Pause, Play, RotateCcw, RotateCw } from 'lucide-react';

export function AudioPlayer({id,title,src,statusLabel='Áudio V2.5'}:{id:string;title:string;src:string;statusLabel?:string}){
  const audio=useRef<HTMLAudioElement>(null); const lastSync=useRef(-1); const [playing,setPlaying]=useState(false); const [duration,setDuration]=useState(0); const [time,setTime]=useState(0); const [speed,setSpeed]=useState(1);
  const key=`pilulas:position:${id}`;
  const sync=async(positionSeconds:number,completed=false)=>{try{await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contentId:id,positionSeconds:Math.max(0,Math.floor(positionSeconds)),completed}),keepalive:true})}catch{/* modo local continua funcionando */}};
  useEffect(()=>{const a=audio.current;if(!a)return; const onLoaded=async()=>{setDuration(a.duration||0);const local=Number(localStorage.getItem(key)||0);let remote=0;try{const res=await fetch(`/api/progress?contentId=${encodeURIComponent(id)}`,{cache:'no-store'});if(res.ok){const data=await res.json();remote=Number(data.positionSeconds||0)}}catch{/* sem conta/rede: usa local */}const saved=Math.max(local,remote);if(saved>0&&saved<a.duration-5){a.currentTime=saved;setTime(saved)}};const onTime=()=>{const current=Math.floor(a.currentTime||0);setTime(a.currentTime);if(current%5===0)localStorage.setItem(key,String(current));if(current>0&&current%15===0&&lastSync.current!==current){lastSync.current=current;void sync(current,false)}};const onEnded=()=>{setPlaying(false);localStorage.removeItem(key);localStorage.setItem(`pilulas:completed:${id}`,'1');void sync(a.duration||a.currentTime,true)};a.addEventListener('loadedmetadata',onLoaded);a.addEventListener('timeupdate',onTime);a.addEventListener('ended',onEnded);return()=>{a.removeEventListener('loadedmetadata',onLoaded);a.removeEventListener('timeupdate',onTime);a.removeEventListener('ended',onEnded)}} ,[id,key]);
  const toggle=()=>{const a=audio.current;if(!a)return;if(a.paused){void a.play();setPlaying(true)}else{a.pause();setPlaying(false);void sync(a.currentTime,false)}};
  const jump=(n:number)=>{const a=audio.current;if(a)a.currentTime=Math.max(0,Math.min(a.duration||0,a.currentTime+n))};
  const format=(n:number)=>`${Math.floor(n/60)}:${Math.floor(n%60).toString().padStart(2,'0')}`;
  return <div className="player-shell"><audio ref={audio} src={src} preload="metadata"/><div className="player-title">{title}</div><div className="player-meta">{statusLabel}</div><div style={{display:'grid',gridTemplateColumns:'auto 1fr auto',gap:12,alignItems:'center',marginTop:16}}><span>{format(time)}</span><input aria-label="Posição do áudio" type="range" min={0} max={duration||0} value={time} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><span>{format(duration)}</span></div><div style={{display:'flex',gap:8,alignItems:'center',marginTop:12,flexWrap:'wrap'}}><button className="btn" onClick={()=>jump(-10)} aria-label="Voltar 10 segundos"><RotateCcw size={16}/>10 s</button><button className="btn" onClick={toggle} aria-label={playing?'Pausar':'Reproduzir'}>{playing?<Pause size={18}/>:<Play size={18}/>} {playing?'Pausar':'Ouvir'}</button><button className="btn" onClick={()=>jump(10)} aria-label="Avançar 10 segundos">10 s<RotateCw size={16}/></button><label className="badge">Velocidade <select value={speed} onChange={e=>{const v=Number(e.target.value);setSpeed(v);if(audio.current)audio.current.playbackRate=v}}><option value="0.75">0,75×</option><option value="1">1×</option><option value="1.25">1,25×</option><option value="1.5">1,5×</option></select></label></div></div>;
}
